name: test
on:
  - pull_request
  - push

jobs:

  test_on_macos:
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2
    - run: xcrun swift test --enable-test-discovery --sanitize=thread

  test_on_ubuntu_xenial:
    container:
      image: vapor/swift:5.2.4-xenial
    runs-on: ubuntu-latest
    steps:
    - run: apt update -y; apt install -y libsqlite3-dev
    - uses: actions/checkout@v2
    - run: swift test --enable-test-discovery --sanitize=thread
